radar:
  numFrames: 0
  num_adc_samples: 256
  num_tx_antennas: 2
  num_rx_antennas: 4
  num_loops_per_frame: 128
  chirps: 128
  sample_rate: 10000
  range_resolution: 0.1954
  iq: 2
  bytes: 2
  num_lvds_lanes: 2
  iq_swap: 0
  ch_interleave: 1

hand_detection:
  min_range: 0.35
  max_range: 1
  threshold_db: 125

paths:
  cmd_path: 'C:\ti\mmwave_studio_02_01_01_00\mmWaveStudio\RunTime\RunCustomScripts.cmd'
  studio_runtime_path: 'C:\ti\mmwave_studio_02_01_01_00\mmWaveStudio\RunTime'
  output_file: 'debug_output.txt'

dca1000:
  static_ip: '192.168.33.30'
  adc_ip: '192.168.33.180'
  data_port: 4098
  config_port: 4096
  CONFIG_HEADER: '5aa5'
  CONFIG_STATUS: '0000'
  CONFIG_FOOTER: 'aaee'

  MAX_PACKET_SIZE: 4096 #max frame size 4096 = 4*256*4 = oneSampleAdcSize*AdcSamples*NumRx -- one chirp
  BYTES_IN_PACKET: 1456
  dataSizeOneChirp: 4096
  dataSizeOneFrame: 524288